// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAu532Uytw2_Sb4eO690w9KfD4dpORcRzU',
    appId: '1:326326432983:web:c9d30aa62ccde3364b2c92',
    messagingSenderId: '326326432983',
    projectId: 'boldproperty-293d5',
    authDomain: 'boldproperty-293d5.firebaseapp.com',
    storageBucket: 'boldproperty-293d5.firebasestorage.app',
    measurementId: 'G-ND3VXP1VKW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBu0bzlwHXwxDkX6NUKr_HNVm2_NvG_RcU',
    appId: '1:326326432983:android:96fb8db3c81514f34b2c92',
    messagingSenderId: '326326432983',
    projectId: 'boldproperty-293d5',
    storageBucket: 'boldproperty-293d5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXpFt9yJIcTXJDLG_AjTmORp3mU2QUguU',
    appId: '1:326326432983:ios:ba20e83d83f1890e4b2c92',
    messagingSenderId: '326326432983',
    projectId: 'boldproperty-293d5',
    storageBucket: 'boldproperty-293d5.firebasestorage.app',
    iosBundleId: 'com.example.ejemplo1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXpFt9yJIcTXJDLG_AjTmORp3mU2QUguU',
    appId: '1:326326432983:ios:ba20e83d83f1890e4b2c92',
    messagingSenderId: '326326432983',
    projectId: 'boldproperty-293d5',
    storageBucket: 'boldproperty-293d5.firebasestorage.app',
    iosBundleId: 'com.example.ejemplo1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAu532Uytw2_Sb4eO690w9KfD4dpORcRzU',
    appId: '1:326326432983:web:8f33245a9fc2e34c4b2c92',
    messagingSenderId: '326326432983',
    projectId: 'boldproperty-293d5',
    authDomain: 'boldproperty-293d5.firebaseapp.com',
    storageBucket: 'boldproperty-293d5.firebasestorage.app',
    measurementId: 'G-H2JFM7JWMH',
  );
}
